awpickupstore_form_configuration:
  path: /awpickupstore/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwPickupStore\Controller\AdminConfigurationController::index'
    _legacy_controller: AdminAwPickupStore
    _legacy_link: AdminAwPickupStore
