services:
  _defaults:
    public: true

  axelweb.awpickupstore.repository.pickup_store:
    class: 'Axelweb\AwPickupStore\Repository\PickupStoreRepository'

  axelweb.awpickupstore.form.type.carrier_entry:
    class: 'Axelweb\AwPickupStore\Form\CarrierEntryType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  axelweb.awpickupstore.form.type.carrier_settings:
    class: 'Axelweb\AwPickupStore\Form\CarrierSettingsFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  axelweb.awpickupstore.form.carrier_settings_data_provider:
    class: 'Axelweb\AwPickupStore\Form\CarrierSettingsFormDataProvider'
    arguments:
      - '@axelweb.awpickupstore.repository.pickup_store'

  axelweb.awpickupstore.form.carrier_settings_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@axelweb.awpickupstore.form.carrier_settings_data_provider'
      - 'Axelweb\AwPickupStore\Form\CarrierSettingsFormType'
      - 'AwPickupStore'

  axelweb.awpickupstore.form.type.schedule:
    class: 'Axelweb\AwPickupStore\Form\ScheduleFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  axelweb.awpickupstore.form.schedule_data_provider:
    class: 'Axelweb\AwPickupStore\Form\ScheduleFormDataProvider'

  axelweb.awpickupstore.form.schedule_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@axelweb.awpickupstore.form.schedule_data_provider'
      - 'Axelweb\AwPickupStore\Form\ScheduleFormType'
      - 'AwPickupStore'

